default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotwire_chat_development

test:
  <<: *default
  database: hotwire_chat_test

production:
  <<: *default
  database: hotwire_chat_production
  username: hotwire_chat
  password: <%= ENV["HOTWIRE_CHAT_DATABASE_PASSWORD"] %>
